### PR TITLE
CanClaim rejects tasks for a period of time.

### LINKED ISSUE #71: Define error handling in Consumer vs. Coordinator
#### Problem

Right now Metafora Consumer retries failed task and command watches and only dies when they return an empty response.

We should spec, doc, define, and implement rules for coordinator implementations about Metafora Consumer's retry logic and conditions.

Related to #70

#### Proposal 1: Retries are implementation specific

I think a sensible route might be for the Consumer to never retry and leave that logic up to implementations. On any error or empty return value the Consumer's Run method would simply exit.

### LINKED ISSUE #93: Balancer.CanClaim and EtcdCoordinator.Watch interact poorly
After a lot of iterations, the etcd Coordinator's Watch() ended up with the simple logic of:

1. Do a recursive GET to find all claimable tasks, return first claimable task
2. If none found, do a blocking Watch

The problem is if a Balancer's CanClaim method rejects a task, Watch will just pick it up all over again. This causes a fast loop (if CanClaim keeps returning `false`) and blocks the affected node from picking up tasks that come *after* the rejected task.

## Solution 1: Report rejected claims to coordinator

``Watch`` could take a ``map[string]struct{}` of tasks to not even consider for claiming.

The issue with this approach is if the balancer changes its mind (e.g. due to cluster state changes or load changes), ``Watch`` may be stuck forever.

## Solution 2: Consider `CanClaim() -> false` a "soft" rejection

...and claim the task anyway after a period of time. See workaround.

## Solution 3: Fix EtcdCoordinator.Watch to only look for new nodes

This creates a new issue of potentially orphaned/invisible unclaimed tasks, but I haven't thought it through.
**helpwanted**

## Workaround

Currently balancer implementations should be exceedingly careful if they return `false` from `CanClaim`.

A workaround is sleeping for a brief period (a second or less) to allow other nodes dibs, and then returning `true`.

### PR DESCRIPTION
**Pull request by schmichael**
**API breaks: Coordinator and Balancer**

This change makes Metafora look uglier in the abstract but actually
handle operational realities better. The existing CanClaim interface
didn't reflect reality: if it rejected a task the Coordinator's Watch
method might just continue returning only that task forever...and in a
tight loop no less! There was no way for the Coordinator's Watch and
Balancer to communicate (unless they implemented shared state outside
the Consumer which sounds really tricky to get right).

This design makes Coordinator.Watch stream claimable tasks back to the
Consumer. The Consumer checks an ignore-list before even calling
Balancer.CanClaim. If a task isn't ignored, CanClaim can cause it to be
ignored until a deadline.

Once the deadline is up *the Consumer handles the task as if it came
from the Coordinator.* This means it gives the Balancer's CanClaim
method another chance to reject it and everything.

Even if `CanClaim` doesn't reject the task again, the task probably
can't be claimed anyway because another node claimed it ages ago.
That's ok. This design trades off being optimally efficient for safety:
it never rejects a task forever (possibly orphaning it), and it never
bypasses the Balancer.

Fixes #93

Errors returned by `Coordinator.Watch` or `Coordinator.Command` are now
**fatal**. Nowhere in our logs could I find an instance of them failing
(even in our flaky staging environment).  I think it's fine to expect
the Coordinator to be resilient and only return errors when *it*
determines it cannot continue to function safely.

Fixes #71

Also makes `DumbBalancer` a singleton because it's silly not to.

### CODE REVIEW

File: balancer.go [hunk 1]
```diff
@@ -89,27 +92,28 @@ type FairBalancer struct {
...
-// released tasks in order to give other nodes a chance to claim them first
-func (e *FairBalancer) CanClaim(taskid string) bool {
-	if e.lastreleased[taskid] {
-		time.Sleep(500 * time.Millisecond)
+// CanClaim will claim any task if this node wasn't over the task threshold
+// during the last rebalance. If it was over the threshold claims will be
+// delayed proportionally.
+func (e *FairBalancer) CanClaim(taskid string) (time.Time, bool) {
+	if e.delay == 0 {
+		return time.Time{}, true
```
Comment (epsniff) [inline balancer.go]: Nit alert!  could we make a const thats like `NoDelay`?   Just to make it read better?

File: ignore.go [hunk 2]
```diff
@@ -0,0 +1,119 @@
+package metafora
+
+import (
+	"container/heap"
+	"sync"
+	"time"
+)
+
+type ignoremgr struct {
```
Comment (epsniff) [inline ignore.go]: This struct needs comments to describe what it does.

Comment (epsniff) [inline ignore.go]: Oh, hey this code looks like the old ttl scheduler :p... sweet!  +1 on `Share Memory By Communicating`.

Comment (schmichael) [inline ignore.go]: Ha, yeah! You were my inspiration! It was tricky to get right though... oof.

File: balancer.go (hunk 1 above)
Comment (schmichael) [inline balancer.go]: Really wish the `time` package just had a `time.Zero` const for things like this. Adding.

File: ignore.go [hunk 3]
```diff
@@ -0,0 +1,119 @@
...
+
+	return ok
+}
+
+func (im *ignoremgr) monitor(tasks chan<- string, stop <-chan struct{}) {
+	times := timeheap{}
+	heap.Init(&times)
+	var next *timetask
+	for {
+		if times.Len() > 0 {
```
Comment (epsniff) [inline ignore.go]: It seems like this block could get simpler if you implemented Peek on your Heap?   But I maybe missing something..

https://github.com/lytics/toolbucket/blob/master/orderedtask/prioityqueue.go#L39

**Comment by epsniff** [comment]
:+1:  - I know its a major change, but if feel cleaner to me.   But that option may change after I implement something on it :p

**Comment by kyledj** [comment]
:seat::seat::seat:
:seat::monkey::seat:
:seat::seat::seat:
